discovery/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        # Overview of identified systems[
        url(r'^$', views.IndexView.as_view(), name='index'),
        # Discovery control interface (trigger to capture traffic
        # on specific interfaces)
        url(r'^control/$', views.ControlView, name='control'),
        # Process PCAP files from predefined folder for analysis
        url(r'^pcap/$', views.PcapView, name='pcap'),
        # Overview of identified systems as table (same as IndexView)
        url(r'^endpoints/$', views.EndpointsView, name='endpoints'),
        # Overview of identified conversations
        # (per IP address and used ports in both directions)
        url(r'^conversations/$', views.ConversationsView, name='conversations'),
        # Queries overview
        url(r'^queries/$', views.QueriesOverviewView, name='queries'),
        # Query: Identification of central systems (many connections to one system)
        url(r'^queries/identifycentralsystems/$', views.QueriesIdentifyCentralSystemsView, name='identifycentralsystems'),
	# Query: MAC address vendors diagram
	url(r'^queries/macaddressvendors/$', views.QueriesMacAddressVendorsView, name='macaddressvendors'),
]       

pythos/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^discovery/', include('discovery.urls', namespace="discovery")),
    url(r'^firewall/', include('firewall.urls', namespace="firewall")),
    url(r'^netflow/', include('netflow.urls', namespace="netflow")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
#    url(r'', include('two_factor.urls', 'two_factor')),
]

discovery/models.py
from django.db import models
from macaddress.fields import MACAddressField

class Net(models.Model):
        """
        Stores a single IP network, related to :model:`config.Origin`, :model:`config.Site`, :model:`discovery.system`.
        """
        origin        = models.ForeignKey('config.Origin', null=True, blank=True)
        site          = models.ForeignKey('config.Site', null=True, blank=True)
        address_inet  = models.GenericIPAddressField(db_index=True, null=True, blank=True, help_text="IP network address")
        mask_inet     = models.GenericIPAddressField(db_index=True, null=True, blank=True, help_text="Subnet mask")
        mask_cidr     = models.IntegerField(null=True, help_text="CIDR prefix")
        address_bcast = models.GenericIPAddressField(db_index=True, null=True, blank=True, help_text="Broadcast address")
        gateway       = models.ForeignKey('Interface', null=True, related_name='gateway_for', help_text="Default gateway")
        netobjects    = models.ManyToManyField('architecture.NetObject', related_name='networks')


class System(models.Model):
        """
        Stores a single system in terms of a machine (be it physical or virtual).
        A system may be related to one or more instances of :model:`discovery.Interface`.
        """
        site          = models.ForeignKey('config.Site', null=True, blank=True)
        name          = models.CharField(max_length=127)
        description   = models.TextField()
        os            = models.ForeignKey('kb.OperatingSystem', null=True, blank=True, help_text="Operating system")


class Interface(models.Model):
        """
        Stores a single interface that may belong to exactly one :model:`discovery.System`.
        Further related to :model:`config.Origin`, :model:`discovery.System`, :model:`discovery.Net`, :model:`architecture.NetObject`.
        """
        origin        = models.ForeignKey('config.Origin', null=True, blank=True)
        system        = models.ForeignKey('System', null=True, blank=True)
        net           = models.ForeignKey('Net', null=True, blank=True)
        address_ether = MACAddressField(integer=False, null=True, blank=True, help_text="Ethernet (MAC) address")
        address_inet  = models.GenericIPAddressField(null=True, blank=True, help_text="IP (v4/v6) address", db_index=True)
        distance      = models.IntegerField(default=-1, help_text="Distance (in hops) from the origin (sensor)")
        protocol_l3   = models.IntegerField(default=0, help_text="OSI layer three protocol")
        tx_pkts       = models.BigIntegerField(default=0, help_text="Number of transmitted packets")
        tx_bytes      = models.BigIntegerField(default=0, help_text="Number of transmitted bytes")
        rx_pkts       = models.BigIntegerField(default=0, help_text="Number of received packets")
        rx_bytes      = models.BigIntegerField(default=0, help_text="Number of received bytes")
        ttl_seen      = models.IntegerField(default=0, help_text="TTL of transmitted packages as seen at the origin (sensor)")
        first_seen    = models.DateTimeField(auto_now=False, null=True, help_text="Timestamp of first occurence")
        last_seen     = models.DateTimeField(auto_now=False, null=True, help_text="Timestamp of last occurence")
        netobjects    = models.ManyToManyField('architecture.NetObject', related_name='interfaces')
        is_global     = models.NullBooleanField(null=True)
        is_private    = models.NullBooleanField(null=True)
        is_multicast  = models.NullBooleanField(null=True)
        is_unspecified = models.NullBooleanField(null=True)
        is_reserved = models.NullBooleanField(null=True)
        is_loopback = models.NullBooleanField(null=True)
        is_link_local = models.NullBooleanField(null=True)

        class Meta:
                unique_together = (('address_ether', 'address_inet', 'origin', 'ttl_seen'),)


class Socket(models.Model):
        """
        Stores a single socket that must belong to exactly one :model:`discovery.Interface`.
        """
        interface     = models.ForeignKey('Interface', related_name='sockets')
        port          = models.IntegerField(default=0)
        protocol_l4   = models.IntegerField(default=0, help_text="OSI layer four protocol")
        services      = models.ManyToManyField('architecture.Service', related_name='sockets')
        service_port  = models.IntegerField(default=0)
        service_detec = models.IntegerField(default=0)
        class Meta:
                unique_together = (('interface', 'port', 'protocol_l4'),)
                index_together = ['port', 'protocol_l4']


class Connection(models.Model):
        """
        Stores a single connection between two instances of :model:`discovery.Socket`.
        """
        src_socket    = models.ForeignKey('Socket', related_name='src_connections')
        dst_socket    = models.ForeignKey('Socket', related_name='dst_connections')
        protocol_l567 = models.IntegerField(default=-1)
        seq           = models.BigIntegerField(default=-1, db_index=True)
        tx_pkts       = models.BigIntegerField(default=0)
        tx_bytes      = models.BigIntegerField(default=0)
        first_seen    = models.DateTimeField(auto_now=False, null=True)
        last_seen     = models.DateTimeField(auto_now=True, null=True)
        closed_flag   = models.BooleanField(default=False)
        syn_flag      = models.BooleanField(default=False)
        class Meta:
                unique_together = (('src_socket', 'dst_socket', 'protocol_l567'),)


class DNScache(models.Model):
        """
        DEPRECATED
        Was used to store a captured DNS query. Will be migrated to :model:`discovery.System` as DNS names are stored there.
        """
        site          = models.ForeignKey('config.Site', default=1)
        address_inet  = models.GenericIPAddressField(db_index=True)
        name          = models.CharField(max_length=253)
        type	      = models.CharField(max_length=15)
        last_seen     = models.DateTimeField(auto_now=True)

discovery/forms.py
from django import forms
from django.conf import settings
import netifaces


class ControlForm(forms.Form):
    INTERFACE_CHOICES = [(iface, iface) for iface in netifaces.interfaces()]

    DURATION_CHOICES = [
            ('5', '5 seconds'),
            ('30', '30 seconds'),
            ('60', '1 minute'),
            ('300', '5 minutes'),
            ('900', '15 minutes'),
            ('3600', '1 hour'),
            ('14400', '4 hours'),
            ('28800', '8 hours'),
            ('86400', '1 day'),
            ('604800', '1 week'),
    ]

    interface = forms.ChoiceField(label='Select interface',
                                  choices=INTERFACE_CHOICES,
                                  widget=forms.Select,
                                  required=True)

    duration = forms.ChoiceField(label='Choose duration',
                                 choices=DURATION_CHOICES,
                                 widget=forms.Select,
                                 required=True)


class PcapForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PcapForm, self).__init__(*args, **kwargs)
        self.fields['filepath'] = forms.FilePathField(label='Select pcap file',
                                                      path=settings.PCAP_FOLDER,
                                                      recursive=True,
                                                      match="\.pcap$",
                                                      allow_files=True,
                                                      allow_folders=False,
                                                      required=True)

        origin_description = forms.CharField(label='Origin description',
                                             required=True)

discovery/views.py
from django.shortcuts import render
from django.views import generic
from django_tables2 import RequestConfig
from django.db.models import Sum, Min, Max, Count
from django.db.models.functions import Substr
from django.db import connection

from redis import Redis
from rq import Queue

from .models import Interface, Connection
from .forms import ControlForm, PcapForm
from .tasks import discovery_task

from discovery.tables import ConversationsTable
from discovery.tables import IdentifyCentralSystemsTable
from discovery.tables import MacAddressVendorsTable

# Overview of identified systems
class IndexView(generic.ListView):
    template_name = 'discovery/index.html'
    context_object_name = 'interface_list'

    def get_queryset(self):
        return Interface.objects.order_by('address_inet')


# Discovery control (trigger to capture traffic on specific interface)
def ControlView(request):
    if request.method == 'POST':
        form = ControlForm(request.POST)
        if form.is_valid():
            capture_interface = form.cleaned_data['interface']
            capture_duration = form.cleaned_data['duration']

            discovery_task.delay(origin_uuid="d44d8aa8c5ef495f992d7531336784fe",
                                 offline=False,
                                 interface=capture_interface,
                                 duration=capture_duration)

            return render(request, 'discovery/control.html', {'form': form})
    else:
            form = ControlForm()

    return render(request, 'discovery/control.html', {'form': form})


# Process PCAP files from predefined folder for analysis
def PcapView(request):
    if request.method == 'POST':
        form = PcapForm(request.POST)
        if form.is_valid():
            filepath = form.cleaned_data['filepath']
            description = "pcap"  # form.cleaned_data['origin_description']

            discovery_task.delay(offline=True,
                                 filepath=filepath,
                                 origin_description=description)

            return render(request, 'discovery/pcap.html', {'form': form})
    else:
        form = PcapForm()

    return render(request, 'discovery/pcap.html', {'form': form})


# Overview of identified systems as table (same as IndexView)
# Something will happen here with charts in near future
def EndpointsView(request):
    interface_objects = Interface.objects.values(
                            'address_inet',
                            'address_ether',
                            'ttl_seen',
                        ).annotate(
                            bytes_total=Sum('tx_bytes',
                                            fields='tx_bytes+rx_bytes'),
                            first_seen=Min('first_seen'),
                            last_seen=Max('last_seen'),
                        ).order_by('-bytes_total')

    # prepare barchart
    xdata = interface_objects.values_list('address_inet', flat=True)[:10]
    ydata = interface_objects.values_list('bytes_total',  flat=True)[:10]

    chartdata = {
        'x': xdata, 'name1': '', 'y1': ydata
    }
    charttype = "discreteBarChart"
    chartcontainer = 'barchart_container'

    return render(
            request,
            'discovery/endpoints.html',
            {
               'endpoints': interface_objects,
               'charttype': charttype,
               'chartdata': chartdata,
               'chartcontainer': chartcontainer
             }
         )


# Overview of identified conversations
# Per IP address and used ports in both directions
def ConversationsView(request):
    table = ConversationsTable(Connection.objects.all())
    RequestConfig(request).configure(table)
    return render(request, 'discovery/conversations.html', {'table': table})


# Queries: Overview
def QueriesOverviewView(request):
    return render(request, 'discovery/queries.html')


# Queries: Identify central systems (by amount of connections to one system)
def QueriesIdentifyCentralSystemsView(request):
    # Result table with overview
    table = IdentifyCentralSystemsTable(Connection.objects.values('dst_socket__interface__address_inet').annotate(dest_ip_counter=Count('dst_socket__interface__address_inet')).order_by('-dest_ip_counter'))


    # D3.js graph
    central_systems_objects_level1 = Connection.objects.values('dst_socket__interface__address_inet').distinct()
    central_systems_objects_level2 = Connection.objects.values('dst_socket__interface__address_inet','src_socket__interface__address_inet').distinct()

    RequestConfig(request).configure(table)
    return render(request, 'discovery/queriesIdentifyCentralSystems.html', {
        'table': table,
        'chartdata_level1' : central_systems_objects_level1,
        'chartdata_level2' : central_systems_objects_level2
        }
    )

# Quereis: MAC address vendors (diagram)
def QueriesMacAddressVendorsView(request):
    # Fetch only vendor part of mac addresses
    mac_addr = Interface.objects.annotate(vendor_part=Substr('address_ether',1,8))
    # Count the vendor part of the mac addresses
    mac_addr = mac_addr.values('vendor_part').annotate(vendor_part_counter=Count('vendor_part')).order_by('-vendor_part_counter')

    # Show output in table
    table = MacAddressVendorsTable(mac_addr)

    # D3.js graph
    # TODO: return JSON file for asynchronous updates

    RequestConfig(request).configure(table)
    return render(request, 'discovery/queriesMacAddressVendors.html', {
        'table': table,
        'macs': mac_addr
        }
    )

discovery/templates/discovery/control.html
<h1>Discovery control interface</h1>

<form action="{% url 'discovery:control' %}" method="post">
<table>
{% csrf_token %}
{{ form }}
<tr><th></th><td><input type="submit" value="Launch" /></td></tr>
</table>
</form>

discovery/templates/discovery/conversations.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" />
    </head>
    <body>
        {% render_table table %}
    </body>
</html>

discovery/templates/discovery/endpoints.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% load nvd3_tags %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" />
        {% include_chart_jscss %}
        {% load_chart charttype chartdata chartcontainer %}
    </head>
    <body>
        {% render_table endpoints %}
        {% include_container chartcontainer 600 1200 %}
    </body>
</html>

discovery/templates/discovery/index.html
{% if interface_list %}
        <ul>
        {% for interface in interface_list %}
                <li>{{ interface.address_inet }}, {{ interface.address_ether }}, {{ interface.last_seen }}</li>
        {% endfor %}
        </ul>
{% else %}
        <p>No interfaces are available.</p>
{% endif %}

discovery/templates/discovery/launch.html
<h1>3..2..1 launched!</h1>

discovery/templates/discovery/pcap.html
<h1>Read pcap file</h1>

<form action="{% url 'discovery:pcap' %}" method="post">
<table>
{% csrf_token %}
{{ form }}
<tr><th></th><td><input type="submit" value="Launch" /></td></tr>
</table>
</form>

discovery/templates/discovery/queries.html
{% load staticfiles %}
<!doctype html>
<html>

    <body>
        <h3>Queries Overview</h3>
	<p>The following queries are available:</p>
	<ul>
		<li><a href="identifycentralsystems/">Identify central systems</a></li>
		<li><a href="macaddressvendors/">MAC address vendors</a></li>
	</ul>
	
    </body>

</html>

discovery/templates/discovery/queriesIdentifyCentralSystems.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" />
        <link rel="stylesheet" href="{% static "discovery/d3_js/diagrams/dendrogram.css" %}" />

	<script src="{% static "discovery/d3_js/d3.js" %}"></script>

    </head>

    <body>
        <h3>Central points of communication</h3>
          <p>Those systems are highlighted that communicate the most with other systems (e.g. proxy server, anti virus server, f
ile server). The pattern used is how many single conversations have the same destination IP and port.</p>
	  <p> TODO: There is an error in the statistics table as the database counts IP addresses multiple times due to the TTL field. We have to clarify how to analyze the data properly or the db layout has to be customized.</p>
          {% render_table table %}

        <h3> Dendrogram (D3.js)</h3>
	<p>The following graphic shows "SERVER" <-> "CLIENT" relationships.
	<p>Based on the example of <a href="http://bl.ocks.org/mbostock/4063570">http://bl.ocks.org/mbostock/4063570</a></p>


	<script>
	  var root_name = "o";

	  // Init JSON array for Tree view of D3.js
	  var chartdata = [ { id: root_name, value : "TEST" } ];
 
	  // Setup the chartdata tree (1st level) - IMPORTANT: Values MUST be unique!!!
	  {% for entry in chartdata_level1 %}
	      	{% if entry.dst_socket__interface__address_inet %}
		  dst = "{{ entry.dst_socket__interface__address_inet }}".replace(/\./g,"-");
		  chartdata.push( { id : root_name + "." + dst, value : "TEST" } );
		{% endif %}
	  {% endfor %}

	  // Setup the chartdata tree (2nd level)
          {% for entry in chartdata_level2 %}
	  	{% if entry.dst_socket__interface__address_inet %}
                  src = "{{ entry.src_socket__interface__address_inet }}".replace(/\./g,"-");
                  dst = "{{ entry.dst_socket__interface__address_inet }}".replace(/\./g,"-");
                  connection = root_name + "." + dst + "." + src ;
                  chartdata.push( { id: connection, value: "TEST" });
		{% endif %}
          {% endfor %}


	</script>

	<svg width="960" height="2000"></svg>

	<script>

var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height"),
    g = svg.append("g").attr("transform", "translate(40,0)");

var tree = d3.cluster()
    .size([height, width - 160]);

var stratify = d3.stratify()
    .parentId(function(d) { return d.id.substring(0, d.id.lastIndexOf(".")); });

  // chartdata = result table from django
  var root = stratify(chartdata)
      .sort(function(a, b) { return (a.height - b.height) || a.id.localeCompare(b.id); });

  tree(root);

  var link = g.selectAll(".link")
      .data(root.descendants().slice(1))
    .enter().append("path")
      .attr("class", "link")
      .attr("d", function(d) {
        return "M" + d.y + "," + d.x
            + "C" + (d.parent.y + 100) + "," + d.x
            + " " + (d.parent.y + 100) + "," + d.parent.x
            + " " + d.parent.y + "," + d.parent.x;
      });

  var node = g.selectAll(".node")
      .data(root.descendants())
    .enter().append("g")
      .attr("class", function(d) { return "node" + (d.children ? " node--internal" : " node--leaf"); })
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })

  node.append("circle")
      .attr("r", 4.5);


  node.append("rect").transition().duration(500).attr("width", 115)
      .attr("height", 25)
      .attr("x", function(d) { 
	     // Root node
	     if (d.parent == null) {
	       return -500;
	     }
	     // Destination IP node
	     else if (d.children) {
	       return -110;
	     }
	     // Source IP node
	     else {
	       return 0;
	     }
      })
      .attr("y", -15)
      .attr("rx", 20)
      .attr("ry", 20)
      .style("fill", "red")
      .style("opacity", "0.3")
      .attr("stroke", "darkred")

  node.append("text")
      .attr("dy", 3)
      .attr("x", function(d) { return d.children ? -8 : 8; })
      .style("text-anchor", function(d) { return d.children ? "end" : "start"; })
      .text(function(d) { return d.id.substring(d.id.lastIndexOf(".") + 1); });


      </script>
	
    </body>

</html>

discovery/templates/discovery/queriesMacAddressVendors.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" />
        <link rel="stylesheet" href="{% static "discovery/d3_js/diagrams/dendrogram.css" %}" />

	<script src="{% static "discovery/d3_js/d3.js" %}"></script>

    </head>

    <body>
        <h3>MAC address vendors</h3>
          {% render_table table %}

        <h3>D3.js</h3>


	{% for mac in macs %}

		{{ mac.vendor_part }} - {{mac.vendor_part_counter }}<BR>

	{% endfor %}

    </body>

</html>